antora:
  extensions:
    - require: '@springio/antora-extensions/root-attachments-extension'
site:
  title: Alex Dev hub
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://www.alexmond.org/
  start_page:  main::index.adoc
  robots: |
      User-agent: *
      Allow: /
      Sitemap: https://www.alexmond.org/sitemap.xml
  keys:
    google_analytics: 'G-KW01QZN663'
content:
  sources:
    - url: ./
      edit_url: false
      branches: main
      worktrees: true
    - url: https://github.com/alexmond/spring-boot-config-json-schema.git
      tags: 1.0.8
      branches: []
      start_path: docs
      edit_url: false
    - url: https://github.com/alexmond/spring-boot-actuator-extensions.git
      branches: []
      tags: 1.0.2
      start_path: docs
      edit_url: false
    - url: https://github.com/alexmond/spring-boot-playground.git
      edit_url: false
      branches: main
      start_path: docs
    - url: https://github.com/alexmond/jsupervisor.git
      edit_url: false
      branches: main
      start_path: docs
    - url: git@github.com:alexmond/yj-schema-validator.git
      branches: [ ]
      tags: 1.0.1
      start_path: docs
      edit_url: false
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.15/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
urls:
  latest_version_segment: current
runtime:
  cache_dir: ./target/antoracache
  log:
    level: info
